name: prague_ru
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  shared_preferences: ^2.5.2
  get:
  flutter_localization: ^0.3.1
  intl: ^0.19.0
  geolocator: ^13.0.2
  google_maps_flutter: ^2.10.0
  collection: ^1.19.0
  geojson_vi: ^2.2.5

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/praga.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/praga.png